### ISSUE TITLE
Cannot download native_client.tar.xz when running ./setup

### ISSUE THREAD

**Issue by davidbelle** [talonvoice/wav2train#3]
Hi. Running ./setup is currently erring out with a 404. See output below. Thanks. 

Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.6.0.cpu/artifacts/public/native_client.tar.xz ...
Traceback (most recent call last):
  File "/1tb/wav2train/DSAlign/bin/taskcluster.py", line 153, in <module>
    main()
  File "/1tb/wav2train/DSAlign/bin/taskcluster.py", line 147, in main
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
  File "/1tb/wav2train/DSAlign/bin/taskcluster.py", line 57, in maybe_download_tc
    urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by lunixbochs** [comment]
Someone needs to sync that part with upstream DSAlign as Mozilla seems to have removed the 0.6 URL

**Comment by davidbelle** [comment]
Ah. 

Is there a workaround in the mean time?
 https://github.com/facebookresearch/wav2letter/issues/737
@tumusudheer  mentioned he downloaded it manually but I can't figure out where in the repo he found it.

**Comment by davidbelle** [comment]
For anyone else looking for a work around:

I was able to get it working by downloading the appropriate native_client tar file from here:

https://github.com/mozilla/DeepSpeech/releases/v0.6.0

Then extract it and copy generate_trie to DSAlign/dependencies/deepspeech/generate_trie
